### PR TITLE
Symfony2 coding standar

### PR DESCRIPTION
**Pull request by pointlessone**
PR for #57.

### CODE REVIEW

**Comment by dblandin** [comment]
Nice. Thanks!

**Comment by dblandin** [comment]
@pointlessone Do we need any remediation point overrides for any checks in this standard? https://github.com/codeclimate/codeclimate-phpcodesniffer/blob/master/Sniffs.php#L13

**Comment by pointlessone** [comment]
@dblandin I don't know. How does one estimate that?

**Comment by dblandin** [comment]
I took a quick look at the sniffs included and I don't think any need an override. We would specific a greater value if an issue requires more time to fix, like a duplication or complexity issue.

**Comment by pointlessone** [comment]
This engine defaults to 70k which is already greater that 50k default in the spec.

**Comment by Jelle-S** [comment]
I can't find this standard anywhere in the documentation. How do I configure it? Is it called 'Symfony', 'Symfony2', something else?

**Comment by pointlessone** [comment]
@Jelle-S It's called "Symfony". Please refer to the plugin [README](https://github.com/djoos/Symfony-coding-standard#readme) for more details.

**Pull request merged**
