### PR TITLE
Update the WordPress Coding Standards and PHP_CodeSniffer to the latest versions

### PR DESCRIPTION
**Pull request by desrosj**
The WordPress Coding Standards PHP_CodeSniffer rules have been updated to version 0.11.0. This pull updates the Composer dependency.

Also, out of curiosity, what happens to issues that are no longer detected when this update is deployed? Do they just disappear? Appear as "fixed" on the next pull request/commit?

### CODE REVIEW

**Comment by desrosj** [comment]
PHP_CodeSniffer version `2.8.1` [fixes a security vulnerability](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/2.8.1) and is [required by the new WordPress Coding Standards rules](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/CHANGELOG.md#changed) version. Added that to the pull request.

**Comment by maxjacobson** [comment]
Hi @desrosj thanks for this PR. Will you rebase this branch on top of master? I just merged #56, which fixes the presenting problem in the CI build

**Comment by maxjacobson** [comment]
> Also, out of curiosity, what happens to issues that are no longer detected when this update is deployed? Do they just disappear? Appear as "fixed" on the next pull request/commit?

If there are checks that are removed in an engine update, those issues will disappear. They're not going to show up as fixed in a PR view, because PR comparisons always show the delta between two analysis "snapshots" that use the same engine versions -- we'll re-analyze the merge base using the updated engine if necessary. Does that make sense?

**Comment by desrosj** [comment]
It does make sense. It would be nice if the issues that go away were listed somewhere, though. There could be a scenario where certain issues are left open for a specific reason, and there could be an ongoing issue or pull request somewhere to fix it. If the issues just disappear, that could be confusing. I guess a feature request :)

**Comment by dblandin** [comment]
@desrosj Thanks for the update!

**Comment by desrosj** [comment]
Just curious, how often do you roll out updates on the site? When can we see this change reflected?

**Comment by dblandin** [comment]
Hey @desrosj,

We usually roll an engine update out soon after a PR is merged into master. A new analysis version including the updates introduced in this PR went out at 3:51pm EST.

You should be able to use the new engine version now on codeclimate.com or via the CLI.

**Comment by maxjacobson** [comment]
Just to add a small thing to that, our goal is to keep our engine docs up-to-date, so you can always reference those, e.g. [the PHP CodeSniffer one](https://docs.codeclimate.com/docs/phpcodesniffer) to see which version is rolled out to production.

**Pull request merged**
