### PR TITLE
Update PHP Codesniffer

### PR DESCRIPTION
**Pull request by fede-moya**
The main purpose of the work is to allow users to run the PSR12 standard.

Sharing here some resources that have been super helpful to address this update and might be useful again in the future. Changes like renaming the old `Runner.php` to `Executor.php` and the rest of the changes can be easily understood by taking a quick look to the links shared below.

- https://github.com/squizlabs/PHP_CodeSniffer/issues/2035
- https://github.com/WPTT/theme-sniffer/blob/806c40759c28519b5e2b6f0ebc38b989a67e22b8/src/callback/class-run-sniffer-callback.php
- https://gist.github.com/gsherwood/aafd2c16631a8a872f0c4a23916962ac

### CODE REVIEW

**Comment by fede-moya** [comment]
@filipesperandio 

 Seems like I don't have the enough permissions for requesting your review, that's why I ping you here. 

Also, you will noticed the I have changed the base docker image `alpine:edge` to an specific version. While using the `alpine:edge` image I suffered from different dns resolutions problems which were not allowing a successful `compose install`, it wasn't able to fetch certain packages. After hours of checking if those packages existed and other potential explanations I ended up changing the base image and it started to work. I didn't perform any further research on that due to the fact that we are a little bit tight regarding schedule. 

I addressed as CC issues as I could, there are some remaining that have been here for a long time, so I think we could temporary ignored them.

One more thing, my idea is to create a `beta` channel for this plugin so I think it would be nice to merge this work against a `beta` branch. Could you create that branch please ? 🙏🏼

**Comment by filipesperandio** [comment]
> Seems like I don't have the enough permissions for requesting your review, that's why I ping you here.

Permissions granted, no need the fork either anymore.

> Also, you will noticed the I have changed the base docker image alpine:edge to an specific version. While using the alpine:edge image I suffered from different dns resolutions problems which were not allowing a successful compose install, it wasn't able to fetch certain packages. After hours of checking if those packages existed and other potential explanations I ended up changing the base image and it started to work. I didn't perform any further research on that due to the fact that we are a little bit tight regarding schedule.

👍 

will look at Circle CI now.

**Comment by filipesperandio** [comment]
I think the circle issue is due to the fork. we don't allow it to pass in credentials to forked PRs.
Now that you have permissions for the repo, can we try pushing a non-forked branch and update the PR? (I don't recall doing it, not sure we can or a new PR is needed)

**Comment by filipesperandio** [comment]
Seems like we can only change base branch... so maybe a new one?

**Comment by filipesperandio** [comment]
`beta` created

**Comment by filipesperandio** [comment]
https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/80 merged into `beta`

**Comment by fede-moya** [comment]
Replaced by https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/83

**Pull request closed without merging**
