### PR TITLE
Feature/magento extension standards

### PR DESCRIPTION
**Pull request by josephdpurcell**
Adds Magento extension sniffs.

Completes issue #51.

### CODE REVIEW

**Comment by josephdpurcell** [comment]
I see the issue was:

```
  [RuntimeException]                                                                                                                   
  Failed to clone https://github.com/magento/marketplace-eqp.git, git was not found, check that it is installed and in your PATH env.  
  sh: git: not found    
```

I just pushed a change to make it "vcs" to see if that fixes it.

**Comment by josephdpurcell** [comment]
Same issue, so trying again using a gzip file. It worked locally, so good luck CircleCI!

**Comment by josephdpurcell** [comment]
Success!

Something to consider in review: Is there a way we can add tests to CircleCI?

For example, we could add a test that runs "phpcs -i" and verifies that the coding standards installed correctly, which would just be validating this output:

```
$ phpcs -i
The installed coding standards are Zend, PEAR, PHPCS, PSR2, MySource, Squiz, PSR1, Drupal, DrupalPractice, WordPress-Docs, WordPress-VIP, WordPress-Core, WordPress, WordPress-Extra, Yii2, MEQP2 and MEQP1
```

**Comment by dblandin** [comment]
Awesome! Thanks for the PR @josephdpurcell!

I think it's reasonable to add `git` as an installed package within this project's `Dockerfile` to address the composer error you ran into.

Should be as simple as adding `git` to the `apk --update add` [command arguments](https://github.com/codeclimate/codeclimate-phpcodesniffer/blob/master/Dockerfile#L6-L15).

> Something to consider in review: Is there a way we can add tests to CircleCI?
>
> For example, we could add a test that runs "phpcs -i" and verifies that the coding standards installed correctly, which would just be validating this output

That would be a great start!

**Comment by josephdpurcell** [comment]
It's failing with error:

```
OK: 24 MiB in 30 packages
/bin/sh: git: not found
The command '/bin/sh -c apk --update add       php7-common       php7-ctype       php7-iconv       php7-json       php7-mbstring       php7-openssl       php7-pcntl       php7-phar       php7-sockets       curl &&       git &&     rm /var/cache/apk/* &&     ln -s /usr/bin/php7 /usr/bin/php' returned a non-zero code: 127
make: *** [image] Error 1
```

It doesn't look like git is getting installed. Any thoughts?

**Comment by josephdpurcell** [comment]
I attempted to follow https://discuss.circleci.com/t/bin-sh-git-not-found/9737 and add openssh, but still git appears to not install.

**Comment by josephdpurcell** [comment]
Doh! Good catch @dblandin! And yes to removing the openssh package.

I'll try to follow up later with tests.

**Pull request merged**
