### PR TITLE
Added support for WordPress coding standards

### LINKED ISSUE #15: Support for WordPress PHP coding standards
Hello,

PHP_CodeSniffer doesn't support WordPress coding standards oob, https://github.com/squizlabs/PHP_CodeSniffer/tree/master/CodeSniffer/Standards.

However these are available here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

Is it possible to add support for WordPress coding standards?

Thanks!

### PR DESCRIPTION
**Pull request by soderlind**
Should fix #15

### CODE REVIEW

**Comment by soderlind** [comment]
The failed checks are not because of my change, please view the error log at CircleCI

**Comment by josephdpurcell** [comment]
I believe rebasing on master will fix the test failures shown in the latest pass.

I have created a similar PR https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/31 for Drupal. Perhaps we can standardize on a similar approach? I like the idea of having separate RUN statements.

One thing you may need to add is the list of sniffs in `Sniffs.php`, otherwise I believe it throws an error. You should be able to generate the list of sniffs with `phpcs -e --standard="WordPress,WordPress-Core,WordPress-Docs,WordPress-Extra,WordPress-VIP"`

**Comment by josephdpurcell** [comment]
I believe https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/34 deprecates the need for this PR.

**Comment by dblandin** [comment]
Hey @soderlind,

We ended up taking a different route here via a composer dependency in #34. Thanks for this PR and enjoy the Wordpress checks! They're available now via the CLI and we should have this out to codeclimate.com sometime tomorrow.

Thanks!

**Comment by dblandin** [comment]
Hey @soderlind,

Just wanted to follow up and let you know that we've released a new engine image to [codeclimate.com]() with the new Wordpress coding standards.

You can enable the standards today by updating your codeclimate.yml configuration file:

```yaml
phpcodesniffer:
  enabled: true
  config:
    standard: "Wordpress"
```

The [full list of supported standards](https://github.com/codeclimate/codeclimate-phpcodesniffer#supported-coding-standards) is now available in our README.

Thanks for the nudge on this!

**Pull request closed without merging**
