### PR TITLE
Abh update codeclimate yml

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
@codeclimate/review This PR updates the `codeclimate.yml` and and `readme` files.

### CODE REVIEW

**Comment by pbrisbin** [comment]
LGTM

**Comment by GordonDiggs** [comment]
Is the analysis error related to the config file?

**Comment by ABaldwinHunter** [comment]
@GordonDiggs I believe the analysis error is related to the config file not being correct.

**Comment by GordonDiggs** [comment]
:+1:

**Pull request merged**
